# fly.toml app configuration file generated for bot-responses-backend-quiet-dawn-7712 on 2025-03-08T20:10:32+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bot-responses-backend-quiet-dawn-7712'
primary_region = 'sin'

[build]
  dockerfile = "Dockerfile"


[deploy]
  strategy = 'rolling'

[env]
  PORT = '5000'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
