app = "talkzilla"

[build]
image = "python:3.12"

[env]
PORT = "8080"

[deploy]
strategy = "rolling"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
